version: "3"

services:
  frontend:
    env_file:
      - .env
    container_name: frontend
    build:
      ./frontend
    ports:
      - "${FRONTEND_SERVICE_PORT}:${FRONTEND_SERVICE_PORT}"
    volumes:
      - ./frontend:/app/frontend
    command: yarn dev
  backend:
    env_file:
      - .env
    container_name: backend
    build:
      ./backend
    ports:
    - "${BACKEND_SERVICE_PORT}:${BACKEND_SERVICE_PORT}"
    volumes:
    - ./backend:/app/backend
    command: python manage.py runserver 0.0.0.0:8000